name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy
